// <auto-generated />
using System;
using EventPlanner.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventPlanner.Migrations.EventosBDMigrations
{
    [DbContext(typeof(EventosBD))]
    [Migration("20240727174529_mssql.azure_migration_690")]
    partial class mssqlazure_migration_690
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EventPlanner.Models.Evento", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Bairro")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Bairro");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)")
                        .HasColumnName("CEP");

                    b.Property<string>("Cidade")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Cidade");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataCriacao");

                    b.Property<DateTime>("DataFinal")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataFinal");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataInicio");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Descricao");

                    b.Property<TimeSpan>("Duracao")
                        .HasColumnType("time")
                        .HasColumnName("Duracao");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Estado");

                    b.Property<byte[]>("FotoDoEvento")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("FotoDoEvento");

                    b.Property<string>("Identificador")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Identificador");

                    b.Property<string>("NomeEvento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("NomeEvento");

                    b.Property<string>("Organizador")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Organizador");

                    b.Property<int?>("QuantAlcool")
                        .HasColumnType("int")
                        .HasColumnName("QuantAlcool");

                    b.Property<int?>("QuantCadeiras")
                        .HasColumnType("int")
                        .HasColumnName("QuantCadeiras");

                    b.Property<int?>("QuantCarne")
                        .HasColumnType("int")
                        .HasColumnName("QuantCarne");

                    b.Property<int?>("QuantCriancas")
                        .HasColumnType("int")
                        .HasColumnName("QuantCriancas");

                    b.Property<int?>("QuantDoces")
                        .HasColumnType("int")
                        .HasColumnName("QuantDoces");

                    b.Property<int?>("QuantMaxPessoas")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("QuantMaxPessoas");

                    b.Property<int?>("QuantMetrosQuadrados")
                        .HasColumnType("int")
                        .HasColumnName("QuantMetrosQuadrados");

                    b.Property<int?>("QuantRefri")
                        .HasColumnType("int")
                        .HasColumnName("QuantRefri");

                    b.Property<int?>("QuantSalgados")
                        .HasColumnType("int")
                        .HasColumnName("QuantSalgados");

                    b.Property<TimeSpan>("TempoAteEvento")
                        .HasColumnType("time")
                        .HasColumnName("TempoAteEvento");

                    b.Property<string>("TipoEvento")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TipoEvento");

                    b.Property<int?>("UsuarioID")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioPremiumID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Evento");
                });
#pragma warning restore 612, 618
        }
    }
}
